// <auto-generated />
using System;
using AppAcademy.Infrastucture.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppAcademy.Infrastucture.Migrations
{
    [DbContext(typeof(AppAcademyDbContext))]
    [Migration("20240927193621_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppAcademy.Domain.Auth.HistorialAcceso", b =>
                {
                    b.Property<string>("HistorialAccesoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DireccionIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dispositivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAcceso")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoAcceso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("HistorialAccesoId");

                    b.HasIndex("UserId");

                    b.ToTable("HistorialAccesos");
                });

            modelBuilder.Entity("AppAcademy.Domain.Auth.Permiso", b =>
                {
                    b.Property<string>("PermisoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamePermiso")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PermisoId");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("AppAcademy.Domain.Auth.RefreshToken", b =>
                {
                    b.Property<string>("RefreshTokenId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("AppAcademy.Domain.Auth.Rol", b =>
                {
                    b.Property<string>("RolId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameRol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AppAcademy.Domain.Auth.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUltimoAcceso")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RolId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("RolId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AppAcademy.Domain.ControlAcademia.Colegiatura", b =>
                {
                    b.Property<string>("ColegiaturaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EstadoColegiatura")
                        .HasColumnType("int");

                    b.Property<string>("EstudianteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ColegiaturaId");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("UserId");

                    b.ToTable("Colegiaturas");
                });

            modelBuilder.Entity("AppAcademy.Domain.ControlAcademia.Estudiante", b =>
                {
                    b.Property<string>("EstudianteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EstudianteId");

                    b.HasIndex("UserId");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("AppAcademy.Domain.ControlAcademia.Materia", b =>
                {
                    b.Property<string>("MateriaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MateriaId");

                    b.HasIndex("UserId");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("AppAcademy.Domain.ControlAcademia.Materia_Estudiante", b =>
                {
                    b.Property<string>("Materia_EstudianteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EstudianteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Faltas")
                        .HasColumnType("int");

                    b.Property<string>("MateriaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Materia_EstudianteId");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("MateriaId");

                    b.HasIndex("UserId");

                    b.ToTable("MateriaEstudiantes");
                });

            modelBuilder.Entity("AppAcademy.Domain.ControlAcademia.MaterialAdeudo", b =>
                {
                    b.Property<string>("MaterialAdeudoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoMaterial")
                        .HasColumnType("int");

                    b.Property<string>("EstudianteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaterialAdeudoId");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("UserId");

                    b.ToTable("MaterialAdeudos");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Categoria", b =>
                {
                    b.Property<string>("CategoriaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Cliente", b =>
                {
                    b.Property<string>("ClienteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Corte", b =>
                {
                    b.Property<string>("CorteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comentarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCorte")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalDevoluciones")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalEfectivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTarjeta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalVales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CorteId");

                    b.HasIndex("UserId");

                    b.ToTable("Cortes");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.DetalleCorte", b =>
                {
                    b.Property<string>("DetalleCorteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CorteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoPago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VentaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DetalleCorteId");

                    b.HasIndex("CorteId");

                    b.HasIndex("VentaId");

                    b.ToTable("DetalleCortes");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.DetallePago", b =>
                {
                    b.Property<string>("DetallePagoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("VentaId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DetallePagoId");

                    b.HasIndex("VentaId");

                    b.ToTable("DetallePagos");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.DetalleVenta", b =>
                {
                    b.Property<string>("DetalleVentaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DescuentoProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("ventaId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DetalleVentaId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("ventaId");

                    b.ToTable("DetalleVentas");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Devolucion", b =>
                {
                    b.Property<string>("DevolucionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VentaId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DevolucionId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UserId");

                    b.HasIndex("VentaId");

                    b.ToTable("Devoluciones");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Entrada", b =>
                {
                    b.Property<string>("EntradaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Bruto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaDeEntrega")
                        .HasColumnType("datetime2");

                    b.Property<string>("Folio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroFactura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrigenId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TotalProductosEntrada")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VencimientoPago")
                        .HasColumnType("int");

                    b.HasKey("EntradaId");

                    b.HasIndex("OrigenId");

                    b.HasIndex("UserId");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.EntradaProducto", b =>
                {
                    b.Property<string>("EntradaProductoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EntradaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductoId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EntradaProductoId");

                    b.HasIndex("EntradaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("EntradaProductos");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.HistorialInventario", b =>
                {
                    b.Property<string>("HistorialInventarioId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CantidadAnterior")
                        .HasColumnType("int");

                    b.Property<int>("CantidadNueva")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("HistorialInventarioId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UserId");

                    b.ToTable("HistorialInventarios");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.HistorialPrecio", b =>
                {
                    b.Property<string>("HistorialPrecioId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioAnterior")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductoId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("HistorialPrecioId");

                    b.HasIndex("ProductoId");

                    b.ToTable("HistorialPrecios");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Inventario", b =>
                {
                    b.Property<string>("InventarioId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InventarioId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Marca", b =>
                {
                    b.Property<string>("MarcaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MarcaId");

                    b.ToTable("Marca");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Producto", b =>
                {
                    b.Property<string>("ProductoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoriaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodigoBarras")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DescuentoBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EstadoProducto")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Impuesto")
                        .HasColumnType("int");

                    b.Property<string>("MarcaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProveedorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.Property<decimal>("Utilidad")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("MarcaId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Promocion", b =>
                {
                    b.Property<string>("PromocionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Descuento")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PromocionId");

                    b.ToTable("Promociones");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Proveedor", b =>
                {
                    b.Property<string>("ProveedorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProveedorId");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Salida", b =>
                {
                    b.Property<string>("SalidaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comentarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalProductosSalida")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SalidaId");

                    b.HasIndex("UserId");

                    b.ToTable("Salidas");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Ubicacion", b =>
                {
                    b.Property<string>("UbicacionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UbicacionId");

                    b.ToTable("Ubicaciones");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Venta", b =>
                {
                    b.Property<string>("ventaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClienteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ventaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UserId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("PermisoRol", b =>
                {
                    b.Property<string>("PermisosPermisoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RolesRolId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PermisosPermisoId", "RolesRolId");

                    b.HasIndex("RolesRolId");

                    b.ToTable("PermisoRol");
                });

            modelBuilder.Entity("ProductoPromocion", b =>
                {
                    b.Property<string>("ProductosProductoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PromocionesPromocionId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductosProductoId", "PromocionesPromocionId");

                    b.HasIndex("PromocionesPromocionId");

                    b.ToTable("ProductoPromocion");
                });

            modelBuilder.Entity("AppAcademy.Domain.Auth.HistorialAcceso", b =>
                {
                    b.HasOne("AppAcademy.Domain.Auth.User", "User")
                        .WithMany("HistorialAccesos")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AppAcademy.Domain.Auth.RefreshToken", b =>
                {
                    b.HasOne("AppAcademy.Domain.Auth.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AppAcademy.Domain.Auth.User", b =>
                {
                    b.HasOne("AppAcademy.Domain.Auth.Rol", "Rol")
                        .WithMany("Users")
                        .HasForeignKey("RolId");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AppAcademy.Domain.ControlAcademia.Colegiatura", b =>
                {
                    b.HasOne("AppAcademy.Domain.ControlAcademia.Estudiante", "Estudiante")
                        .WithMany("Colegiaturas")
                        .HasForeignKey("EstudianteId");

                    b.HasOne("AppAcademy.Domain.Auth.User", "User")
                        .WithMany("Colegiaturas")
                        .HasForeignKey("UserId");

                    b.Navigation("Estudiante");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AppAcademy.Domain.ControlAcademia.Estudiante", b =>
                {
                    b.HasOne("AppAcademy.Domain.Auth.User", "User")
                        .WithMany("Estudiantes")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AppAcademy.Domain.ControlAcademia.Materia", b =>
                {
                    b.HasOne("AppAcademy.Domain.Auth.User", "User")
                        .WithMany("Materias")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AppAcademy.Domain.ControlAcademia.Materia_Estudiante", b =>
                {
                    b.HasOne("AppAcademy.Domain.ControlAcademia.Estudiante", "Estudiante")
                        .WithMany("MateriaSEstudiantes")
                        .HasForeignKey("EstudianteId");

                    b.HasOne("AppAcademy.Domain.ControlAcademia.Materia", "Materia")
                        .WithMany("MateriasEstudiantes")
                        .HasForeignKey("MateriaId");

                    b.HasOne("AppAcademy.Domain.Auth.User", "User")
                        .WithMany("MateriasEstudiantes")
                        .HasForeignKey("UserId");

                    b.Navigation("Estudiante");

                    b.Navigation("Materia");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AppAcademy.Domain.ControlAcademia.MaterialAdeudo", b =>
                {
                    b.HasOne("AppAcademy.Domain.ControlAcademia.Estudiante", "Estudiante")
                        .WithMany("MaterialAdeudos")
                        .HasForeignKey("EstudianteId");

                    b.HasOne("AppAcademy.Domain.Auth.User", "User")
                        .WithMany("MaterialAdeudos")
                        .HasForeignKey("UserId");

                    b.Navigation("Estudiante");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Corte", b =>
                {
                    b.HasOne("AppAcademy.Domain.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.DetalleCorte", b =>
                {
                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Corte", "Corte")
                        .WithMany("DetalleCortes")
                        .HasForeignKey("CorteId");

                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Venta", "Venta")
                        .WithMany("DetalleCortes")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corte");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.DetallePago", b =>
                {
                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Venta", "Venta")
                        .WithMany("DetallePagos")
                        .HasForeignKey("VentaId");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.DetalleVenta", b =>
                {
                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Producto", "Producto")
                        .WithMany("DetalleVentas")
                        .HasForeignKey("ProductoId");

                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Venta", "Venta")
                        .WithMany("DetalleVentas")
                        .HasForeignKey("ventaId");

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Devolucion", b =>
                {
                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Producto", "Producto")
                        .WithMany("Devoluciones")
                        .HasForeignKey("ProductoId");

                    b.HasOne("AppAcademy.Domain.Auth.User", "User")
                        .WithMany("Devoluciones")
                        .HasForeignKey("UserId");

                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Venta", "Venta")
                        .WithMany("Devoluciones")
                        .HasForeignKey("VentaId");

                    b.Navigation("Producto");

                    b.Navigation("User");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Entrada", b =>
                {
                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Ubicacion", "Origen")
                        .WithMany("Entradas")
                        .HasForeignKey("OrigenId");

                    b.HasOne("AppAcademy.Domain.Auth.User", "User")
                        .WithMany("Entradas")
                        .HasForeignKey("UserId");

                    b.Navigation("Origen");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.EntradaProducto", b =>
                {
                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Entrada", "Entrada")
                        .WithMany()
                        .HasForeignKey("EntradaId");

                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Producto", "Producto")
                        .WithMany("EntradaProductos")
                        .HasForeignKey("ProductoId");

                    b.Navigation("Entrada");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.HistorialInventario", b =>
                {
                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Producto", "Producto")
                        .WithMany("HistorialInventarios")
                        .HasForeignKey("ProductoId");

                    b.HasOne("AppAcademy.Domain.Auth.User", "User")
                        .WithMany("HistorialInventarios")
                        .HasForeignKey("UserId");

                    b.Navigation("Producto");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.HistorialPrecio", b =>
                {
                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Producto", "Producto")
                        .WithMany("HistorialPrecios")
                        .HasForeignKey("ProductoId");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Inventario", b =>
                {
                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Producto", "Producto")
                        .WithMany("Inventarios")
                        .HasForeignKey("ProductoId");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Producto", b =>
                {
                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId");

                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Marca", "Marca")
                        .WithMany("Productos")
                        .HasForeignKey("MarcaId");

                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Proveedor", "Proveedor")
                        .WithMany("Productos")
                        .HasForeignKey("ProveedorId");

                    b.Navigation("Categoria");

                    b.Navigation("Marca");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Salida", b =>
                {
                    b.HasOne("AppAcademy.Domain.Auth.User", "User")
                        .WithMany("Salidas")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Venta", b =>
                {
                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Cliente", "Cliente")
                        .WithMany("Ventas")
                        .HasForeignKey("ClienteId");

                    b.HasOne("AppAcademy.Domain.Auth.User", "User")
                        .WithMany("Ventas")
                        .HasForeignKey("UserId");

                    b.Navigation("Cliente");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PermisoRol", b =>
                {
                    b.HasOne("AppAcademy.Domain.Auth.Permiso", null)
                        .WithMany()
                        .HasForeignKey("PermisosPermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppAcademy.Domain.Auth.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolesRolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductoPromocion", b =>
                {
                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductosProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Promocion", null)
                        .WithMany()
                        .HasForeignKey("PromocionesPromocionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppAcademy.Domain.Auth.Rol", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AppAcademy.Domain.Auth.User", b =>
                {
                    b.Navigation("Colegiaturas");

                    b.Navigation("Devoluciones");

                    b.Navigation("Entradas");

                    b.Navigation("Estudiantes");

                    b.Navigation("HistorialAccesos");

                    b.Navigation("HistorialInventarios");

                    b.Navigation("MaterialAdeudos");

                    b.Navigation("Materias");

                    b.Navigation("MateriasEstudiantes");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Salidas");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("AppAcademy.Domain.ControlAcademia.Estudiante", b =>
                {
                    b.Navigation("Colegiaturas");

                    b.Navigation("MateriaSEstudiantes");

                    b.Navigation("MaterialAdeudos");
                });

            modelBuilder.Entity("AppAcademy.Domain.ControlAcademia.Materia", b =>
                {
                    b.Navigation("MateriasEstudiantes");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Cliente", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Corte", b =>
                {
                    b.Navigation("DetalleCortes");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Marca", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Producto", b =>
                {
                    b.Navigation("DetalleVentas");

                    b.Navigation("Devoluciones");

                    b.Navigation("EntradaProductos");

                    b.Navigation("HistorialInventarios");

                    b.Navigation("HistorialPrecios");

                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Proveedor", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Ubicacion", b =>
                {
                    b.Navigation("Entradas");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Venta", b =>
                {
                    b.Navigation("DetalleCortes");

                    b.Navigation("DetallePagos");

                    b.Navigation("DetalleVentas");

                    b.Navigation("Devoluciones");
                });
#pragma warning restore 612, 618
        }
    }
}
