// <auto-generated />
using System;
using AppAcademy.Infrastucture.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppAcademy.Infrastucture.Migrations
{
    [DbContext(typeof(AppAcademyDbContext))]
    [Migration("20250128162549_RemoveAndAddedNewModels")]
    partial class RemoveAndAddedNewModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppAcademy.Domain.ControlAcademia.Colegiatura", b =>
                {
                    b.Property<string>("ColegiaturaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("EstadoColegiatura")
                        .HasColumnType("int");

                    b.Property<string>("EstudianteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ColegiaturaId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("Colegiaturas");
                });

            modelBuilder.Entity("AppAcademy.Domain.ControlAcademia.Estudiante", b =>
                {
                    b.Property<string>("EstudianteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoEstudiante")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstudianteId");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("AppAcademy.Domain.ControlAcademia.Materia", b =>
                {
                    b.Property<string>("MateriaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MateriaId");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("AppAcademy.Domain.ControlAcademia.Materia_Estudiante", b =>
                {
                    b.Property<string>("Materia_EstudianteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EstudianteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Faltas")
                        .HasColumnType("int");

                    b.Property<string>("MateriaId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Materia_EstudianteId");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("MateriaId");

                    b.ToTable("MateriaEstudiantes");
                });

            modelBuilder.Entity("AppAcademy.Domain.ControlAcademia.MaterialAdeudo", b =>
                {
                    b.Property<string>("MaterialAdeudoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoMaterial")
                        .HasColumnType("int");

                    b.Property<string>("EstudianteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaterialAdeudoId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("MaterialAdeudos");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Categoria", b =>
                {
                    b.Property<string>("CategoriaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Cliente", b =>
                {
                    b.Property<string>("ClienteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Corte", b =>
                {
                    b.Property<string>("CorteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comentarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCorte")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalDevoluciones")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalEfectivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTarjeta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalVales")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CorteId");

                    b.ToTable("Cortes");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.DetalleCorte", b =>
                {
                    b.Property<string>("DetalleCorteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CorteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EstadoCorte")
                        .HasColumnType("int");

                    b.Property<int>("EstadoTipoPago")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DetalleCorteId");

                    b.HasIndex("CorteId");

                    b.ToTable("DetalleCortes");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.DetalleVenta", b =>
                {
                    b.Property<string>("DetalleVentaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VentaId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DetalleVentaId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("DetalleVentas");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Entrada", b =>
                {
                    b.Property<string>("EntradaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Bruto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaDeEmision")
                        .HasColumnType("datetime2");

                    b.Property<string>("Folio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroFactura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalProductosEntrada")
                        .HasColumnType("int");

                    b.HasKey("EntradaId");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.EntradaProducto", b =>
                {
                    b.Property<string>("EntradaProductoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EntradaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductoId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EntradaProductoId");

                    b.HasIndex("EntradaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("EntradaProductos");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Inventario", b =>
                {
                    b.Property<string>("InventarioId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InventarioId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Marca", b =>
                {
                    b.Property<string>("MarcaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MarcaId");

                    b.ToTable("Marca");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Producto", b =>
                {
                    b.Property<string>("ProductoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoriaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodigoBarras")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DescuentoBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EstadoProducto")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Impuesto")
                        .HasColumnType("int");

                    b.Property<string>("MarcaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProveedorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.Property<decimal>("Utilidad")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("MarcaId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Proveedor", b =>
                {
                    b.Property<string>("ProveedorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProveedorId");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Salida", b =>
                {
                    b.Property<string>("SalidaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comentarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalProductosSalida")
                        .HasColumnType("int");

                    b.HasKey("SalidaId");

                    b.ToTable("Salidas");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Venta", b =>
                {
                    b.Property<string>("VentaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Bruto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClienteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EstadoTipoPago")
                        .HasColumnType("int");

                    b.Property<int>("EstadoVenta")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Neto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalProductos")
                        .HasColumnType("int");

                    b.HasKey("VentaId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AppAcademy.Domain.ControlAcademia.Colegiatura", b =>
                {
                    b.HasOne("AppAcademy.Domain.ControlAcademia.Estudiante", "Estudiante")
                        .WithMany("Colegiaturas")
                        .HasForeignKey("EstudianteId");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("AppAcademy.Domain.ControlAcademia.Materia_Estudiante", b =>
                {
                    b.HasOne("AppAcademy.Domain.ControlAcademia.Estudiante", "Estudiante")
                        .WithMany("MateriaSEstudiantes")
                        .HasForeignKey("EstudianteId");

                    b.HasOne("AppAcademy.Domain.ControlAcademia.Materia", "Materia")
                        .WithMany("MateriasEstudiantes")
                        .HasForeignKey("MateriaId");

                    b.Navigation("Estudiante");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("AppAcademy.Domain.ControlAcademia.MaterialAdeudo", b =>
                {
                    b.HasOne("AppAcademy.Domain.ControlAcademia.Estudiante", "Estudiante")
                        .WithMany("MaterialAdeudos")
                        .HasForeignKey("EstudianteId");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.DetalleCorte", b =>
                {
                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Corte", "Corte")
                        .WithMany("DetalleCortes")
                        .HasForeignKey("CorteId");

                    b.Navigation("Corte");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.DetalleVenta", b =>
                {
                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Producto", "Producto")
                        .WithMany("DetalleVentas")
                        .HasForeignKey("ProductoId");

                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Venta", "Venta")
                        .WithMany("DetalleVentas")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.EntradaProducto", b =>
                {
                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Entrada", "Entrada")
                        .WithMany("EntradaProductos")
                        .HasForeignKey("EntradaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Producto", "Producto")
                        .WithMany("EntradaProductos")
                        .HasForeignKey("ProductoId");

                    b.Navigation("Entrada");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Inventario", b =>
                {
                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Producto", "Producto")
                        .WithMany("Inventarios")
                        .HasForeignKey("ProductoId");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Producto", b =>
                {
                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId");

                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Marca", "Marca")
                        .WithMany("Productos")
                        .HasForeignKey("MarcaId");

                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Proveedor", "Proveedor")
                        .WithMany("Productos")
                        .HasForeignKey("ProveedorId");

                    b.Navigation("Categoria");

                    b.Navigation("Marca");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Venta", b =>
                {
                    b.HasOne("AppAcademy.Domain.PuntoDeVenta.Cliente", "Cliente")
                        .WithMany("Ventas")
                        .HasForeignKey("ClienteId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppAcademy.Domain.ControlAcademia.Estudiante", b =>
                {
                    b.Navigation("Colegiaturas");

                    b.Navigation("MateriaSEstudiantes");

                    b.Navigation("MaterialAdeudos");
                });

            modelBuilder.Entity("AppAcademy.Domain.ControlAcademia.Materia", b =>
                {
                    b.Navigation("MateriasEstudiantes");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Cliente", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Corte", b =>
                {
                    b.Navigation("DetalleCortes");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Entrada", b =>
                {
                    b.Navigation("EntradaProductos");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Marca", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Producto", b =>
                {
                    b.Navigation("DetalleVentas");

                    b.Navigation("EntradaProductos");

                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Proveedor", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("AppAcademy.Domain.PuntoDeVenta.Venta", b =>
                {
                    b.Navigation("DetalleVentas");
                });
#pragma warning restore 612, 618
        }
    }
}
